# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://118.69.188.126:5432/scsms?currentSchema=dev
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
        format_sql: true
        show_sql: true
    show-sql: true
logging:
  sensitive-fields: ${SENSITIVE_DATA:accessToken, refreshToken, phoneNumber,email}
  level:
    com.kltn.scsms_api_service: TRACE
    root: warn
    web: debug

app:
  cors:
    allowed-origin-patterns: "http://localhost:3000,http://localhost:3001,http://localhost:8080,http://127.0.0.1:3000,http://127.0.0.1:3001,http://localhost:5173,http://127.0.0.1:5173,http://localhost:4200,http://127.0.0.1:4200,https://*.vercel.app,https://*.netlify.app"
